language: python

matrix:
  include:
  - python: 3.8
    dist: bionic
    env: TOXENV=py38
  - python: nightly
    dist: bionic
    env: TOXENV=py39
  allow_failures:
  - env: TOXENV=py39

before_install:
  - npm install -g aws-cdk@next
  - python -m pip install --upgrade setuptools pip virtualenv

# command to install dependencies
install:
  - pip install -r requirements.txt

scripts:
  - echo TODO
